- pkgs/hydra/default.nix
Hydra internally uses `nixUnstable`, which got updated to a newer version in the nixos-19-09-small channel a few days ago. This contained a breaking change, which caused the hydra build to fail. 
This PR pins the nixpkgs version to the latest commit in the nixos-19-09-small channel which still works with hydra.
> Hydra: Pin nixpkgs version

- pkgs/initrd-creator/lib/qemu-test
- pkgs/initrd-creator/lib/qemu-test.nix
This MR moves complexity from the expect script to the nix-script.
This allows multiple boot configurations of qemu. e.G to boot with a hypervisor underneath, without changing the expect script.
> Allow custom qemu configuration for initrd tests

- pkgs/initrd-creator/lib/qemu-test
Currently we boot a kernel and initrd in QEMU with 2 Gigabytes of main memory.
We run in some  trouble with initrd's with size larger than 250 MB compressed and 750MB uncompressed.
This MR increases the main memory that is passed to QEMU to 4 Gigabytes to boot larger initrd images.
> qemu-test: increase main memory size

- pkgs/initrd-creator/lib/qemu-test
Currently, we have to pass ticks in the initrd string when there are spaces in it.
This MR circumvents this issue as it moves the tick encapsulation to the expect script.
> expect: update script for simpler use

- pkgs/initrd-creator/lib/qemu-test.nix
Currently the test initrd build fails, because of some additional ticks that aren't removed in the last MR.
This MR removes the additional ticks that leads to the failing tests.
> qemu-test: remove additional ticks in command line configuration

- pkgs/initrd-creator/lib/qemu-test
- pkgs/initrd-creator/lib/qemu-test.nix
Currently, there is no way to specify QEMU configuration options from outside the test script.
This PR makes the test runs dynamically configurable from different tests.
> qemu-tests: make qemu arguments more configureable

- nix/sources.json
Bump Nixpkgs from random unstable from January to a recent version of 20.03 stable.
> nixpkgs: bump to recent 20.03

- pkgs/run-sotest/src/run_sotest/__main__.py
Users of run_sotest used to run it with `python -u` to get unbuffered output and see the sotest URL while the script kept polling for results. Handle this in the script itself by manual flushing.
> Flush URL to console while waiting in run_sotest

- lib/patched-make-initrd.nix
This allows us to build ramdisks with microcode updates attached to them.
> makeInitrd: Add support for prepend

- lib/sotest.nix
- pkgs/sotest-testruns/default.nix
Previously we had nix (or in other projects python) code that generates both a sotest project config and a zip bundle in parallel. In the end, both had to work together.
This pull requests extends the sotest library in a way that you can now:
- create a sotest project config that uses nix store paths to reference binaries
- run this through the `projectBundleFromTestrunClosure` function and automatically get the zip bundle and an adapted project config that works with this zip file.
you can see the working result here: https://opensource.sotest.io/results/83
i also gave the initrds descriptive names, that is not yet visible in the sotest test run.
> sotest lib: generate zip bundle from test run description closure

- default.nix
The overlays list itself needs to be exported so it can be used as overlays over nixpkgs like so:
```nix
let
pkgs = import nixpkgs { overlays = (import cbspkgs {}).overlays; };
in pkgs.hello
```
> default.nix: Export overlays

- lib/writers.nix
Currently, shellcheck fails with error code SC1091 when sourcing a file that is not in the FILES environment variable of shellcheck.
This PR allows files that are not listed in the FILES environment variable.
> Allow external files in shellcheck

- modules/default.nix
- nix/cyberus-overlay-function.nix
- nix/cyberus-overlay.nix
in order to have access to modules that each of our projects exports in one uniform way, i added `pkgs.cbspkgs.nixosModules` merging.
> Export nixos modules

- pkgs/initrd-creator/image_defs/kernel-compile-initrd.nix
when this repository is run on basis of nixos 21.05, then a linux kernel 5.10 is built which comes with new include dependencies.
this issue uncovered the same problem: https://github.com/NixOS/nixpkgs/issues/91609
this PR puts the suggested fix in place. i tried this on top of nixos 20.09 and 21.05 and both works.
(the internal MR on our private cbspkgs shows the latter)
> Make kernel compile initrd run with NixOS 21.05's linux kernel version

- nix/sources.json
- nix/sources.nix
- pkgs/ipxe/default.nix
- pkgs/run-sotest/default.nix
- pkgs/run-sotest/src/run_sotest/__main__.py
This PR updates the nixpkgs channel to nixos-21.11 and applies the necessary changes to this repository. 
In particular, these changes include:
1. `stdenv.lib` has been removed in favor of `lib`
2. black received a change which removes leading and trailing whitespace in docstrings: https://github.com/psf/black/pull/1740
> Update to nixpkgs 21.11

- lib/sotest.nix
The existing `projectBundleFromTestrunClosure` functionality used for creating project bundles from a nix expression has a few disadvantages:
1. It is a bit overeager in choosing which paths to include in the zip archive (#33)
2. It strips the `/nix/store` prefix unconditionally from all referenced paths, even ones that should not be changed  (#26)
3. Its interface is a bit weird, taking a derivation, while you would expect to be able to use it like this:
`projectBundleFromTestrunClosure { boot_items: [ ... ]; tags: [ ... ]; }`.
This PR introduces a new function `mkProjectBundle`, which solves these issues:
Only paths referenced at the start of a `boot_item`'s `exec`, load`, or `extra_files` entries are included in the ZIP archive, and only these paths are changed in the resulting …
> lib: Add mkProjectBundle

- lib/sotest.nix
#34 contained a bug in the newly introduced deprecation warning, which breaks our internal pipelines.
In particular, this happens:
```
$ nix-env -f default.nix -i run-sotest
error: value is a string while a list was expected, at /path/to/cbspkgs-public/lib/sotest.nix:78:6
(use '--show-trace' to show detailed location information)
```
These changes fix the problem:
```
$ nix-env -f default.nix -i run-sotest
trace: warning: Using projectBundleFromTestrunClosure is deprecated. Use mkProjectBundle instead.
replacing old 'run-sotest-1.0.0'
installing 'run-sotest-1.0.0'
```
> lib: fix string concatenation in deprecation warning

- pkgs/run-sotest/src/run_sotest/__main__.py
SoTest now uses new routes for accessing test run results, this switches the displayed route from `/results/` to `/test_runs/`.
> run_sotest: Use new results link at `test_runs`

- pkgs/run-sotest/default.nix
- pkgs/run-sotest/src/run_sotest/__main__.py
This PR switches the `run_sotest` script over to the new SoTest API layout and therefore gets rid of the old `/api/` routes.
The new version of `/api/query`, `/test_runs/<id>/status` now returns an HTTP 400 status code when the Test Run could not be found.
The version number has been increased to `1.1.0`, although I'm not sure if there are any additional consequences of that change.
There's an internal MR with an integration test for the new script as well that's been executed with these changes.
> Switch run_sotest to new Web UI API routes

- lib/sotest.nix
- pkgs/sotest-testruns/default.nix
This removes the deprecated functionality that has been replaced by the new function introduced in #34.
This PR contains in particular: 
- changing the sotest-testruns package to use the new functionality
- removing all the deprecated functionality from the sotest lib
- as a drive-by change, running nixpkgs-fmt on all changed nix files
[Here is our internal pipeline](https://gitlab.vpn.cyberus-technology.de/mnapierkowski/cbspkgs/-/pipelines/53164) for changes that bump all relevant repositories to the latest version, to ensure this PR doesn't remove any functionality that is still in use:
> Remove old sotest package creation functionality

- pkgs/run-sotest/src/run_sotest/__main__.py
- pkgs/run-sotest/src/run_sotest/poll_app.py
- pkgs/run-sotest/src/run_sotest/poll_test_run.py
- pkgs/run-sotest/src/setup.py
This adds some new parameters to enable users to upload boot files directly with the Test Run creation.
The parameter `boot_files` now accepts either a URL to some files or a file path to local files.
There's a new parameter `testrun_id_file`, which is a path to a file where the test run id is stored. This is needed for reliably exporting the test run id when no polling is used.
A new `poll_sotest` script that only polls a test run without requiring all of the parameters for test run creation. This script needs the test run id to work.
There's an internal integration test that uses the new script. I'd really appreciate some user feedback on how well this works both for pipeline and manual use.
> run_sotest: Enable direct boot_files upload
